# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# DOCKER COMPOSE BUILDER FOR FLOWKIT
#

version: '3.5'

services:

  flowdb:
    image: flowminder/flowdb:${CONTAINER_TAG:-latest}
    build:
      context: .
      dockerfile: flowdb.Dockerfile
    environment:
      MAPBOX_ACCESS_TOKEN: "pk.eyJ1IjoibXlsZW5lc2NoIiwiYSI6ImNscWdrZnZ3OTE3Y2cyanJxZHM4dXN3cmoifQ.Jk2bRJD9c1m6wgslAM5ppg"

  flowmachine:
    image: flowminder/flowmachine:${CONTAINER_TAG:-latest}
    build:
      context: .
      dockerfile: flowmachine.Dockerfile
    environment:
      MAPBOX_ACCESS_TOKEN: "pk.eyJ1IjoibXlsZW5lc2NoIiwiYSI6ImNscWdrZnZ3OTE3Y2cyanJxZHM4dXN3cmoifQ.Jk2bRJD9c1m6wgslAM5ppg"

  worked_examples:
    container_name: worked_examples
    image: flowminder/flowkit-examples:${CONTAINER_TAG:-latest}
    build:
      context: .
      dockerfile: examples.Dockerfile
    environment:
      MAPBOX_ACCESS_TOKEN: "pk.eyJ1IjoibXlsZW5lc2NoIiwiYSI6ImNscWdrZnZ3OTE3Y2cyanJxZHM4dXN3cmoifQ.Jk2bRJD9c1m6wgslAM5ppg"

  flowapi:
    image: flowminder/flowapi:${CONTAINER_TAG:-latest}
    build:
      context: .
      dockerfile: flowapi.Dockerfile
    environment:
      MAPBOX_ACCESS_TOKEN: "pk.eyJ1IjoibXlsZW5lc2NoIiwiYSI6ImNscWdrZnZ3OTE3Y2cyanJxZHM4dXN3cmoifQ.Jk2bRJD9c1m6wgslAM5ppg"

  flowauth:
    image: flowminder/flowauth:${CONTAINER_TAG:-latest}
    build:
      context: .
      dockerfile: flowauth.Dockerfile
    environment:
      MAPBOX_ACCESS_TOKEN: "pk.eyJ1IjoibXlsZW5lc2NoIiwiYSI6ImNscWdrZnZ3OTE3Y2cyanJxZHM4dXN3cmoifQ.Jk2bRJD9c1m6wgslAM5ppg"

  flowetl:
    image: flowminder/flowetl:${CONTAINER_TAG:-latest}
    build:
      context: .
      dockerfile: flowetl.Dockerfile
    environment:
      MAPBOX_ACCESS_TOKEN: "pk.eyJ1IjoibXlsZW5lc2NoIiwiYSI6ImNscWdrZnZ3OTE3Y2cyanJxZHM4dXN3cmoifQ.Jk2bRJD9c1m6wgslAM5ppg"
